service: front-scheduler-v5
runtime: custom
env: flex
handlers:
  - url: /.*
    script: this field is required, but ignored
# Application Resources
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs 
      size_gb: 0.5
# Automatic Scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

